# Generated by Django 2.0 on 2018-12-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('storage', models.CharField(default='Temporary - deleted after import to database', max_length=255)),
                ('file_type', models.CharField(default='CSV', max_length=255)),
                ('header_line', models.CharField(blank=True, max_length=3)),
                ('separator', models.CharField(blank=True, max_length=8)),
                ('table', models.CharField(blank=True, max_length=100)),
                ('database', models.CharField(blank=True, max_length=100)),
                ('database_username', models.CharField(blank=True, max_length=100)),
                ('database_password', models.CharField(blank=True, max_length=100)),
                ('database_ip', models.CharField(blank=True, max_length=100)),
                ('database_port', models.CharField(blank=True, max_length=100)),
                ('database_sid', models.CharField(blank=True, max_length=100)),
                ('database_db', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
