# Generated by Django 2.0 on 2018-12-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_auto_20181210_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='error',
            field=models.CharField(blank=True, default='', max_length=100000, null=True),
        ),
    ]
