# Generated by Django 2.0 on 2018-12-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fileupload', '0006_auto_20181218_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(default='', max_length=128, verbose_name='Original filename'),
            preserve_default=False,
        ),
    ]
