# Generated by Django 2.0 on 2018-12-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fileupload', '0008_remove_document_uploading_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='task_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
