# Generated by Django 2.0 on 2018-12-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fileupload', '0009_document_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='percent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file_storage',
            field=models.CharField(blank=True, default='Temporary - deleted after import to database', max_length=255,
                                   null=True),
        ),
    ]
