# Generated by Django 2.0 on 2018-12-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0010_auto_20181228_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='percent',
            field=models.IntegerField(null=True),
        ),
    ]
