# Generated by Django 2.0 on 2019-01-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fileupload', '0011_auto_20181228_2148'),
    ]

    def resave_all_documents(apps, schema_editor):
        Document = apps.get_model('fileupload', 'Document')
        for document in Document.objects.all():
            document.save()

    operations = [
        migrations.AddField(
            model_name='document',
            name='db_connection',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.RunPython(resave_all_documents),
    ]
