# Generated by Django 2.0 on 2019-01-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0012_document_db_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='percent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
