# Generated by Django 2.0 on 2019-01-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fileupload', '0013_auto_20190105_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_header_line',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
