---
kind: pipeline
name: default

steps:
- name: telegram-notify-start-build
  image: appleboy/drone-telegram
  settings:
    secrets:
    - telegram_token
    to: 57439615
    format: markdown
    message: >
        🕒 Начинаем собирать `{{repo.name}} - {{commit.branch}} rev.{{build.number}}`.


        Автор - {{commit.author}}.


        В случае успешной сборки проект будет размещен по [ссылке](https://{{commit.branch}}.{{repo.name}}.squizduos.ru)


        Комментарий доступен ниже. Ссылка на коммит [прилагается](https://gogs.squizduos.ru/squizduos/{repo.name}/commit/{{commit.sha}}).


        `{{commit.message}}`
