pipeline:
    telegram-notify-start-build:
        image: appleboy/drone-telegram
        secrets:
          - telegram_token
        to: 
         - 57439615
        message: >
            Начинаем собирать {{repo.name}}, ветка  [#{{build.number}}]({{build.link}})
        when:
            branch: master

    build:
        image: docker/compose:1.9.0
        commands:
         - docker-compose build --no-cache
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        when:
            branch: master

    deploy-local:
        image: docker/compose:1.9.0
        commands:
          - docker-compose up -d
          - docker system prune
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        when:
            branch: master
            status:  [ success ]
    
    telegram-notify-deploy-finished:
        image: appleboy/drone-telegram
        secrets:
          - telegram_token
        to: 
         - 57439615
        message: >
            {{#success build.status}}
                Попытка собрать {{repo.name}} номер [#{{build.number}}]({{build.link}}) успешна! Заходи и наслаждайся :-)
            {{else}}
                Попытка собрать {{repo.name}} номер [#{{build.number}}]({{build.link}}) провалилась :-( Срочно пни @squizduos.
            {{/success}}
        when:
            branch: master
            status:  [ failure, success ]

