pipeline:
    telegram-notify-start-build:
        image: appleboy/drone-telegram
        secrets:
          - telegram_token
        to: 
         - 57439615
        format: markdown
        message: >
            🕒 Начинаем собирать `{{repo.name}} - {{commit.branch}} rev.{{build.number}}`.

            Автор - {{commit.author}}.
            
            Комментарий доступен ниже. Ссылка на коммит - [прилагается](https://gogs.squizduos.ru/squizduos/img-test/commit/{{commit.sha}})
            
            `{{commit.message}}`
        when:
            branch: master

    build:
        image: docker/compose:1.9.0
        commands:
         - docker-compose build
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        when:
            branch: master
    
    telegram-notify-start-deploy:
        image: appleboy/drone-telegram
        secrets:
          - telegram_token
        to: 
         - 57439615
        format: markdown
        message: >
            {{#success build.status}}
            ⚠️ **Внимание! Заливка!**
            
            В ближайшие 20 секунд сервис [img-test](http://img-test.squizduos.ru) может быть недоступен. Приносим свои извинения.
            {{else}}
            ❌ Сборка проекта `{{repo.name}} - {{commit.branch}} rev.{{build.number}}` не удалась.

            Виновник торжества - {{commit.author}}. Коммит [прилагается](https://gogs.squizduos.ru/squizduos/img-test/commit/{{commit.sha}}).

            Детальный лог доступен по [ссылке]({{build.link}}). 

            Сервис продолжает работу в стабильном режиме по адресу [http://img-test.squizduos.ru](http://img-test.squizduos.ru).
            {{/success}}
        when:
            branch: master
            status:  [ success ]

    deploy-local:
        image: docker/compose:1.9.0
        commands:
          - docker-compose up -d
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        when:
            branch: master
            status:  [ success ]
    
    telegram-notify-deploy-finished:
        image: appleboy/drone-telegram
        secrets:
          - telegram_token
        to: 
         - 57439615
        format: markdown
        message: >
            {{#success build.status}}
            Сборка проекта `{{repo.name}} - {{commit.branch}} rev.{{build.number}}` успешно завершена.

            Сборка проекта шла с {{datetime build.started "15:04:05" "GMT+3"}} по {{datetime build.finished "15:04:05" "GMT+3"}} {{datetime build.finished "01.02.2006" "GMT+3"}} г.
            
            Детальный лог доступен по [ссылке]({{build.link}}).

            Сервис возобновил свою работу на [http://img-test.squizduos.ru](http://img-test.squizduos.ru).
            {{else}}
            ❌ **ВНИМАНИЕ! ВНИМАНИЕ!**

            Попытка запуска неудачная! Сервис [http://img-test.squizduos.ru](http://img-test.squizduos.ru) недоступен.

            Немедленно сообщите @squizduos.
            {{/success}}
        when:
            branch: master
            status:  [ failure, success ]

