version: '2'
services:
    db:
        image: postgres
        volumes:
             - pgdata:/var/lib/postgresql/data
    oracle:
        image: wnameless/oracle-xe-11g
        expose:
            - 49161
        environment:
            - ORACLE_ALLOW_REMOTE=true
        volumes:
            - ordata:/opt/oracle/oradata
    web:
        build: .
        command: bash docker-entrypoint.sh
        expose:
            - 8000
        environment:
            - VIRTUAL_HOST=img-test.squizduos.ru
            - VIRTUAL_PORT=8000
            - LETSENCRYPT_HOST=img-test.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com
        depends_on:
    adminer:
        image: adminer
        restart: always
        expose:
            - 8080
        environment:
            - VIRTUAL_HOST=img-db.squizduos.ru
            - VIRTUAL_PORT=8080
            - LETSENCRYPT_HOST=img-db.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com


volumes:
  pgdata:
  ordata:

networks:
  default:
    external:
      name: nginx-proxy
