version: '2'
services:
    db:
        image: postgres
        volumes:
             - pgdata:/var/lib/postgresql/data
    oracle:
        image: wnameless/oracle-xe-11g
        ports:
            - 49161:1521
        environment:
            ORACLE_ALLOW_REMOTE=true
    web:
        build: .
        command: bash docker-entrypoint.sh
        volumes:
            - .:/code
        ports:
            - "8001:8000"
        depends_on:
            - db
        dns: 8.8.8.8
    adminer:
        image: adminer
        restart: always
        ports:
        - 8002:8080

volumes:
    pgdata:

docker run -d -p 49161:1521 -e ORACLE_ALLOW_REMOTE=true wnameless/oracle-xe-11g
