version: '2'
services:
    db:
        image: postgres
    web:
        build: .
        command: bash docker-entrypoint.sh
        volumes:
            - .:/code
        ports:
            - "8001:8000"
        depends_on:
            - db
