version: '2'
services:
    db:
        image: postgres
        volumes:
            - imgdownloader_pgdata_${BRANCH}:/var/lib/postgresql/data
    web:
        build: .
        command: bash docker-entrypoint.sh
        expose:
            - 8000
        environment:
            - VIRTUAL_HOST=${BRANCH}.img-test.squizduos.ru
            - VIRTUAL_PORT=8000
            - LETSENCRYPT_HOST=${BRANCH}.img-test.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com
        volumes:
            - imgdownloader_media_data_${BRANCH}:/code/media
            - imgdownloader_log_data_${BRANCH}:/code/log
    celery:
        build: .
        command: celery worker -l info -A imgdownloader
        volumes:
            - imgdownloader_media_data_${BRANCH}:/code/media
            - imgdownloader_log_data_${BRANCH}:/code/log
    adminer:
        image: adminer
        restart: always
        expose:
            - 8080
        environment:
            - VIRTUAL_HOST=${BRANCH}.img-db.squizduos.ru
            - VIRTUAL_PORT=8080
            - LETSENCRYPT_HOST=${BRANCH}.img-db.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com
    redis:
        image: redis:latest
        volumes:
            - imgdownloader_redis_data_${BRANCH}:/data
    celery-flower:
        build: .
        command:  celery flower -A imgdownloader --address=0.0.0.0 --port=5555 
        expose:
            - 5555
        volumes:
            - imgdownloader_media_data_${BRANCH}:/code/media
            - imgdownloader_log_data_${BRANCH}:/code/log
        environment:
            - VIRTUAL_HOST=${BRANCH}.img-tasks.squizduos.ru
            - VIRTUAL_PORT=5555
            - LETSENCRYPT_HOST=${BRANCH}.img-tasks.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com


volumes:
  imgdownloader_pgdata_${BRANCH}:
  imgdownloader_redis_data_${BRANCH}:
  imgdownloader_media_data_${BRANCH}:
  imgdownloader_log_data_${BRANCH}:

networks:
  default:
    external:
      name: nginx-proxy
