version: '2'
services:
    db:
        image: postgres
    web:
        build: .
        command: bash docker-entrypoint.sh
        expose:
            - 8000
        environment:
            - VIRTUAL_HOST=ec2-18-191-152-229.us-east-2.compute.amazonaws.com
            - VIRTUAL_PORT=8000
            - LETSENCRYPT_HOST=ec2-18-191-152-229.us-east-2.compute.amazonaws.com
            - LETSENCRYPT_EMAIL=squizduos@gmail.com
        depends_on:
            - db

networks:
  default:
    external:
      name: nginx-proxy
