version: '2'
services:
    db:
        image: postgres
        volumes:
             - pgdata:/var/lib/postgresql/data
    oracle:
        image: wnameless/oracle-xe-11g
        ports:
            - 49161:1521        
        expose:
            - 49161
        environment:
            - ORACLE_ALLOW_REMOTE=true
        volumes:
            - ordata:/u01/app/oracle/oradata/XE/
    web:
        build: .
        command: bash docker-entrypoint.sh
        expose:
            - 8000
        environment:
            - VIRTUAL_HOST=img-test.squizduos.ru
            - VIRTUAL_PORT=8000
            - LETSENCRYPT_HOST=img-test.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com
    adminer:
        image: adminer
        restart: always
        expose:
            - 8080
        environment:
            - VIRTUAL_HOST=img-db.squizduos.ru
            - VIRTUAL_PORT=8080
            - LETSENCRYPT_HOST=img-db.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com
    redis:
        image: redis:latest
        volumes:
             - redis_data:/data


volumes:
  pgdata:
  ordata:
  redis_data:

networks:
  default:
    external:
      name: nginx-proxy
