version: '2'
services:
    db:
        image: postgres
        volumes:
             - pgdata:/var/lib/postgresql/data
    oracle:
        image: wnameless/oracle-xe-11g
        ports:
            - 49161:1521
            - 8004:8080
        expose:
            - 1521
        environment:
            - ORACLE_ALLOW_REMOTE=true
            - ORACLE_ENABLE_XDB=true
    web:
        build: .
        command: bash docker-entrypoint.sh
        volumes:
            - .:/code
        ports:
            - "8001:8000"
            - "3000:3000"
        depends_on:
            - db
        dns: 8.8.8.8
    
    redis:
        image: redis:latest

    celery:
        build: .
        command: celery worker -l info -A imgdownloader 
        volumes:
        - '.:/code'

    adminer:
        image: adminer
        restart: always
        ports:
        - 8002:8080

    celery-flower:
        build: .
        command:  celery flower -A imgdownloader --address=0.0.0.0 --port=5555 
        ports:
            - "8003:5555"
        volumes:
        - '.:/code'
        


volumes:
    pgdata:
    ordata: