version: '2'
services:
    db:
        image: postgres
        volumes:
             - pgdata:/var/lib/postgresql/data
    oracle:
        image: wnameless/oracle-xe-11g       
        expose:
            - 49161
        ports:
            - 1521
        environment:
            - ORACLE_ALLOW_REMOTE=true
            - ORACLE_ENABLE_XDB=true
    web:
        build: .
        command: bash docker-entrypoint.sh
        expose:
            - 8000
        environment:
            - VIRTUAL_HOST=${BRANCH}.img-test.squizduos.ru
            - VIRTUAL_PORT=8000
            - LETSENCRYPT_HOST=${BRANCH}.img-test.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com
        volumes:
            - media_data:/code/media
            - log_data:/code/log
    celery:
        build: .
        command: celery worker -l info -A imgdownloader
        volumes:
            - media_data:/code/media
            - log_data:/code/log
    adminer:
        image: adminer
        restart: always
        expose:
            - 8080
        environment:
            - VIRTUAL_HOST=${BRANCH}.img-db.squizduos.ru
            - VIRTUAL_PORT=8080
            - LETSENCRYPT_HOST=${BRANCH}.img-db.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com
    redis:
        image: redis:latest
        volumes:
             - redis_data:/data
    celery-flower:
        build: .
        command:  celery flower -A imgdownloader --address=0.0.0.0 --port=5555 
        expose:
            - 5555
        volumes:
            - media_data:/code/media
            - log_data:/code/log
        environment:
            - VIRTUAL_HOST=${BRANCH}.img-tasks.squizduos.ru
            - VIRTUAL_PORT=5555
            - LETSENCRYPT_HOST=${BRANCH}.img-tasks.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com


volumes:
  pgdata:
  ordata:
  redis_data:
  media_data:
  log_data:

networks:
  default:
    external:
      name: nginx-proxy
