version: '2'
services:
    db:
        image: postgres
        volumes:
            - imgdownloader_pgdata_restapi:/var/lib/postgresql/data
    web:
        build: .
        command: bash docker-entrypoint.sh
        expose:
            - 8000
        environment:
            - VIRTUAL_HOST=restapi.img-test.squizduos.ru
            - VIRTUAL_PORT=8000
            - LETSENCRYPT_HOST=restapi.img-test.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com
        volumes:
            - imgdownloader_media_data_restapi:/code/media
            - imgdownloader_log_data_restapi:/code/log
    celery:
        build: .
        command: celery worker -l info -A imgdownloader
        volumes:
            - imgdownloader_media_data_restapi:/code/media
            - imgdownloader_log_data_restapi:/code/log
    adminer:
        image: adminer
        restart: always
        expose:
            - 8080
        environment:
            - VIRTUAL_HOST=restapi.img-db.squizduos.ru
            - VIRTUAL_PORT=8080
            - LETSENCRYPT_HOST=restapi.img-db.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com
    redis:
        image: redis:latest
        volumes:
            - imgdownloader_redis_data_restapi:/data
    celery-flower:
        build: .
        command:  celery flower -A imgdownloader --address=0.0.0.0 --port=5555 
        expose:
            - 5555
        volumes:
            - imgdownloader_media_data_restapi:/code/media
            - imgdownloader_log_data_restapi:/code/log
        environment:
            - VIRTUAL_HOST=restapi.img-tasks.squizduos.ru
            - VIRTUAL_PORT=5555
            - LETSENCRYPT_HOST=restapi.img-tasks.squizduos.ru
            - LETSENCRYPT_EMAIL=squizduos@gmail.com


volumes:
  imgdownloader_pgdata_restapi:
  imgdownloader_redis_data_restapi:
  imgdownloader_media_data_restapi:
  imgdownloader_log_data_restapi:

networks:
  default:
    external:
      name: nginx-proxy
