# Generated by Django 2.0 on 2018-11-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentitcation', '0003_user_login_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='username'),
        ),
    ]
