# Generated by Django 2.0 on 2018-11-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentitcation', '0004_auto_20181129_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='is_staff'),
        ),
    ]
